services:
  app:
    build: . # 현재 폴더의 Dockerfile을 실행
    container_name: foodtrip
    ports:
      - 8080:8080
    networks:
      - foodtrip
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=foodtrip
      - SPRING_DATASOURCE_PASSWORD=java1234
    depends_on:
      - oracle
    restart: always

  oracle:
    image: gvenzl/oracle-xe:18
    container_name: oracle
    ports:
      - 1521:1521
    networks:
      - foodtrip
    environment:
      - ORACLE_PASSWORD=java1234
      - APP_USER=foodtrip
      - APP_USER_PASSWORD=java1234
    volumes:
      - myoracle:/opt/oracle/oradata
    restart: always

networks:
  foodtrip:

volumes:
  myoracle:
