spring:
  config:
    import: optional:application-secret.yml

  h2:
    console:
      enabled: true
      path: /h2-console

    datasource:
      url: jdbc:h2:~/food
      driver-class-name: org.h2.Driver
      username: sa
      password:

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true
          show_sql: true

  # Thymeleaf ??
  thymeleaf:
    cache: false  # ?? ????? false, ?? ????? true ??
    mode: HTML
    encoding: UTF-8

  # ?? ?? ??
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# MyBatis ??
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.test.domain
  configuration:
    map-underscore-to-camel-case: true

# ?? ??
server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ?? ??
logging:
  level:
    root: INFO
    com.test: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
